### ISSUE TITLE
Try to run spec2017 has error:AttributeError: Class HPI_BP has no parameter 'BTBEntries'

### ISSUE THREAD

**Issue by NiJiazhe** [dhschall/gem5-fdp#3]
Hi sir:
I want to run spec2017 based on fdp-hello.py.Part of my configuration is like this:

```
from m5.util import addToPath
addToPath("../")
from common import Options
Options.addCommonOptions(parser)
Options.addSEOptions(parser)
```
I need to use --warmup-insts=1000000 -I 2000000 because spec2017 is too large.When I run the script I get the error:

```
AttributeError: Class HPI_BP has no parameter 'BTBEntries'

At:
  src/python/m5/SimObject.py(408): __setattr__
  src/python/m5/SimObject.py(293): __init__
  /home/ronnie/Projects/riscv-fs/gem5-fdp/configs/common/cores/arm/HPI.py(1682): <module>
```

But HPI_BP has BTBEntries.How can I solve this?Or can this build FDP based on gem5-fdp/configs/deprecated/example/se.py？
Hope for your information!Thanks~

**Comment by NiJiazhe** [comment]
Or can this build FDP based on se.py？

**Comment by NiJiazhe** [comment]
By the way, if I use 
```
from m5.util import addToPath
addToPath("../")
from common import Options
Options.addCommonOptions(parser)
Options.addSEOptions(parser)
```
and
```
# Lastly we run the simulation.
simulator = Simulator(board=board)
simulator.run()
```
there will be an error:
```
Exception: The banned module 'common.Options' has been included. Please do not use this in your simulations. Reason: The options provided by 'Options' are not compatible with the gem5 standard library.

At:
  src/python/gem5/simulate/simulator.py(441): run
  /home/ronnie/Projects/riscv-fs/gem5-fdp/configs/spec2017/fdp_spec2017.py(535): <module>
  src/python/m5/main.py(630): main
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

```
I find the simulator.py ban the common.Options. So which start simulation should I use?Or  I want to build fdp based on gem5-fdp/configs/deprecated/example/se.py but I don't know how to make this.
Thanks~

**Comment by dhschall** [comment]
Hi @NiJiazhe,
the HPI configuration bug has been fixed while those changes where upstreamed into the `develop` branch. However, I have not merged back the changes yet.
Refer to https://github.com/gem5/gem5/blob/82b5c332b7aeb04f365f6d5d6cfbe725139228c5/configs/common/cores/arm/HPI.py#L1683

However, the `SimpleBTB` is not working here yet. Try to add this:
```
class HPI_BTB(AssociativeBTB):
    numEntries = 128

class HPI_BP(TournamentBP):
    BTB = HPI_BTB()
```

**Comment by NiJiazhe** [comment]
Thanks for the reply!I'll continue to work on it。
